name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Run cake
        run: |
          dotnet new tool-manifest
          dotnet tool install Cake.Tool
          dotnet tool restore
          dotnet cake